INTEGRATIONS_INFO_1 = '/html/body/main/div[1]'
INTEGRATIONS_INFO_2 = '/html/body/main/div[3]'
GENERATE_GRAPHIC = '/html/body/main/form/div/div[3]/button'
FILTER_BTN = '/html/body/main/div[2]/div/div/div/button'
INTEGRATION_FILTER = '/html/body/main/form/div/div[2]/div/button'
PERIOD_FILTER = '/html/body/main/div[2]/div/div/div/button'