EXECUTIONS_TAB = '/html/body/aside/nav/ul/a[2]'
ALL_PROCESSES = '/html/body/main/div[1]/div/a[2]'
PROCESS_TITLE = '/html/body/main/div[2]/div[1]/div[1]/div[1]/h6'
OPEN_LIST_BTN = '/html/body/main/form/div/div[1]/div/button'
SHOW_LIST_BTN = '/html/body/main/form/div/div[2]/button'
EXECUTION_TITLE = '/html/body/main/div[2]/div[1]/div[1]/div[1]/div/div[1]/h6'
FILTER_BTN = '/html/body/main/div[2]/div[1]/div[1]/div[2]/div/div/button'
